# Generated by Erlang.mk. Edit at your own risk!

src/rabbit_exchange_type_json.erl:: /Users/lucas.polesello/Documents/dev_plugins/rabbitmq-json-filters-exchange/deps/rabbit_common/include/rabbit.hrl /Users/lucas.polesello/Documents/dev_plugins/rabbitmq-json-filters-exchange/deps/rabbit_common/include/resource.hrl src/json_filter.erl; @touch $@

COMPILE_FIRST += json_filter
